### ISSUE TITLE
building/template

### ISSUE THREAD

**Issue by Frank18000** [BrandonWill/GrepolisBot#11]
Building and template doesn´t work

**Comment by BrandonWill** [comment]
Is there an error you're getting? I tested and it works on my end. Make sure you're saving the town before you save the template. 


![image](https://cloud.githubusercontent.com/assets/949047/17214078/3c0f7648-54a5-11e6-8136-bf4100bbfed4.png)

**Comment by Frank18000** [comment]
20:58:39 1afarmers are disabled!
20:58:43 1a  ild or building queue is full!
20:58:49 021.1a 16 bireme to queue!
island_x: 696
island_y: 499
Wood: 744
Stone: 20449
Iron: 29220
Storage: 32100 full: false
WARNING: 20:58:50 2a wasn't found! Bot is removing it from the list of current towns.
WARNING: 20:58:50  3a wasn't found! Bot is removing it from the list of current towns.
WARNING: 20:58:50 4a wasn't found! Bot is removing it from the list of current towns.


this is wat i see know
after this the saves are empty there was an updat on the worlds

**Comment by BrandonWill** [comment]
If you're still getting those messages, you're using an older version of the bot. I've updated 0.19 about 4 times

**Comment by BrandonWill** [comment]
Here's what mine currently looks like from starting a new world:
Error loading TroopSave.txt
Error loading DocksSave.txt
Error loading FarmersSave.txt
16:45:41 Browser agent changed to latest chrome version. It's now: Mozilla/5.0 (
Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.8
4 Safari/537.36
16:45:51 Selecting world
16:45:54 csrftoken: xxxxxxxxxxxxxx
16:45:54 Default town: xxxxx
SEVERE: 16:45:54 --------Captain wasn't found!-----
16:45:55 Towns found: 1
16:46:02 Bot enabled
16:46:03 001 farmers are disabled!
16:46:06 001 Nothing to build or building queue is full!

**Comment by Frank18000** [comment]
to be shure i downloaded the zip file 5 minutes ago and tested it. The same effect

**Comment by BrandonWill** [comment]
Are you stopping the bot before replacing the file? If you're still receiving the messages telling you the number of iron and stuff, it's still the older version

**Comment by BrandonWill** [comment]
Which world are you playing on? I've tried it on several newer worlds, including the ones with the newer farming systems (you just have to put mood at 100 for those)

**Comment by Frank18000** [comment]
nl40

**Comment by BrandonWill** [comment]
Alright, I started on the newest version of the server you were playing. On a new zip file. Here's what I see:

16:55:01 Browser agent changed to latest chrome version. It's now: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.84 Safari/537.36
16:55:20 Selecting world
16:55:24 csrftoken: xxxxx
16:55:24 Default town: xxxxx
16:55:24 --------Captain wasn't found!-----
16:55:24 Towns found: 1
16:55:32 Bot enabled
16:55:34 Stad van 001 farmers are disabled!
16:55:37 Stad van 001 Nothing to build or building queue is full!

**Comment by Frank18000** [comment]
the other thing i can think of is my connection to the network is bad

**Comment by BrandonWill** [comment]
The bot waits for the server to respond before acting on anything. I think you're still using the older version somehow (maybe your system is keeping a cache of it?) because of the messages that you've received. I'll change it to 0.20, and hopefully it'll work correctly for you

**Comment by Frank18000** [comment]
okay

**Comment by BrandonWill** [comment]
Alright, 0.20 is out

**Comment by BrandonWill** [comment]
Everything seems to be working on my end, let me know!

16:59:30 Browser agent changed to latest chrome version. It's now: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.84 Safari/537.36
16:59:40 Selecting world
16:59:44 csrftoken: xxxxxx
16:59:44 Default town: xxxxx
16:59:44 --------Captain wasn't found!-----
16:59:44 Towns found: 1
16:59:48 Bot enabled
16:59:56 Stad van 001 Nothing to build or building queue is full!


17:06:29 The farming village "Gadrana" was farmed successfully!
17:06:32 Stad van 001 Nothing to build or building queue is full!


17:11:43 Default town: xxxxx
17:11:43 --------Captain wasn't found!-----
17:13:14 The farming village "Gadrana" was farmed successfully!
17:13:17 Stad van 001 Nothing to build or building queue is full!


17:17:12 Default town: xxxxx
17:17:12 --------Captain wasn't found!-----
17:19:41 The farming village "Drapsi" was farmed successfully!
17:19:42 The farming village "Gadrana" was farmed successfully!
17:19:45 Stad van 001 Nothing to build or building queue is full!


17:25:22 The farming village "Drapsi" was farmed successfully!
17:25:23 The farming village "Gadrana" was farmed successfully!
17:25:25 Stad van 001 Senate has been added to the building queue!


17:31:28 The farming village "Drapsi" was farmed successfully!
17:31:29 The farming village "Gadrana" was farmed successfully!
17:31:33 Stad van 001 Senate has been added to the building queue!

**Comment by Frank18000** [comment]
i have update the bot and jave but the same result. I also tested it from a clear instal en didn´t use an old game save

08:37:54 xxxxxxxx farmers are disabled!
08:37:57 xxxxxxxxx Nothing to build or building queue is full!
08:38:03 xxxxxx farmers are disabled!
08:38:05 xxxxxx Nothing to build or building queue is full!
08:38:11 xxxxxx farmers are disabled!
08:38:14 xxxxxxx Nothing to build or building queue is full!
08:38:16 xxxxxxx added 85 slinger to queue!
08:38:16 xxxxxxl wasn't found! Bot is removing it from the list of current towns.
08:38:16 xxxxxx  wasn't found! Bot is removing it from the list of current towns.
08:38:16 xxxxxxx wasn't found! Bot is removing it from the list of current towns.
08:38:16 xxxxxx wasn't found! Bot is removing it from the list of current towns.

**Comment by BrandonWill** [comment]
I can't reproduce this problem. Did you happen to update to Windows 10? I'm not sure if the bot would work on that operating system

**Comment by Frank18000** [comment]
i am working in windows 10. But i was doing that for a wile so that can't be the problem i think. The java version is the same. I think the problem is the wifi system where i am on. So i wil test when i am home again

**Comment by BrandonWill** [comment]
Hmm, alright. I'm mostly curious because I did change the way files were saved and loaded. I am using some Java 8 techniques though which may cause some problems (mainly in the building template method), do you have any previous versions of java installed? They aren't usually uninstalled when you install later versions, so that may be part of the problem as well

**Comment by BrandonWill** [comment]
The most recent bot version won't let you run without Java 8 or higher right now. It sends an error message; this will eliminate that possibility if you're still running into errors.

**Comment by Frank18000** [comment]
Exception in thread "JavaFX Application Thread" java.lang.IllegalArgumentException: No enum constant Grepolis.Researches.ResearchType.{c
        at java.lang.Enum.valueOf(Unknown Source)
        at Grepolis.Researches$ResearchType.valueOf(Researches.java:32)
        at Grepolis.Research.parseHTML(Research.java:57)
        at Grepolis.GrepolisBot$10$1.handle(GrepolisBot.java:1312)
        at Grepolis.GrepolisBot$10$1.handle(GrepolisBot.java:1242)
        at com.sun.javafx.webkit.UIClientImpl.lambda$dispatchWebEvent$54(UIClientImpl.java:99)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.sun.javafx.webkit.UIClientImpl.dispatchWebEvent(UIClientImpl.java:98)
        at com.sun.javafx.webkit.UIClientImpl.alert(UIClientImpl.java:157)
        at com.sun.webkit.WebPage.fwkAlert(WebPage.java:2220)
        at com.sun.webkit.network.URLLoader.twkDidFinishLoading(Native Method)
        at com.sun.webkit.network.URLLoader.notifyDidFinishLoading(URLLoader.java:838)
        at com.sun.webkit.network.URLLoader.lambda$didFinishLoading$98(URLLoader.java:829)
        at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
        at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191)
        at java.lang.Thread.run(Unknown Source)


this is the error i get with the latest version

**Comment by BrandonWill** [comment]
Should now give you an error message to help me fix it while not crashing. I don't have an account on the older worlds to test

**Comment by Frank18000** [comment]
15:13:52 Error in finding research within the following data: {c:Researches
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
        at Grepolis.Research.parseHTML(Research.java:65)
        at Grepolis.GrepolisBot$10$1.handle(GrepolisBot.java:1331)
        at Grepolis.GrepolisBot$10$1.handle(GrepolisBot.java:1242)
        at com.sun.javafx.webkit.UIClientImpl.lambda$dispatchWebEvent$54(UIClientImpl.java:99)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.sun.javafx.webkit.UIClientImpl.dispatchWebEvent(UIClientImpl.java:98)
        at com.sun.javafx.webkit.UIClientImpl.alert(UIClientImpl.java:157)
        at com.sun.webkit.WebPage.fwkAlert(WebPage.java:2220)
        at com.sun.webkit.network.URLLoader.twkDidFinishLoading(Native Method)
        at com.sun.webkit.network.URLLoader.notifyDidFinishLoading(URLLoader.java:838)
        at com.sun.webkit.network.URLLoader.lambda$didFinishLoading$98(URLLoader.java:829)
        at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
        at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191)
        at java.lang.Thread.run(Unknown Source)

this is the eror now

**Comment by BrandonWill** [comment]
that error should now be fixed

**Comment by Frank18000** [comment]
it gives this error

15:25:49 Error in finding research within the following data: {c:Researches
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
        at Grepolis.Research.parseHTML(Research.java:65)
        at Grepolis.GrepolisBot$10$1.handle(GrepolisBot.java:1331)
        at Grepolis.GrepolisBot$10$1.handle(GrepolisBot.java:1242)
        at com.sun.javafx.webkit.UIClientImpl.lambda$dispatchWebEvent$54(UIClientImpl.java:99)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.sun.javafx.webkit.UIClientImpl.dispatchWebEvent(UIClientImpl.java:98)
        at com.sun.javafx.webkit.UIClientImpl.alert(UIClientImpl.java:157)
        at com.sun.webkit.WebPage.fwkAlert(WebPage.java:2220)
        at com.sun.webkit.network.URLLoader.twkDidFinishLoading(Native Method)
        at com.sun.webkit.network.URLLoader.notifyDidFinishLoading(URLLoader.java:838)
        at com.sun.webkit.network.URLLoader.lambda$didFinishLoading$98(URLLoader.java:829)
        at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
        at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191)
        at java.lang.Thread.run(Unknown Source)

**Comment by Frank18000** [comment]
i don´t have captain at this moment. But the farming is of so that shoulden´t be the problem

**Comment by BrandonWill** [comment]
Captainless farming was implemented for the newer servers, but I'm not sure if it'll work on the older ones.

And no, the error is coming from it looking for your researches. I'll disable it for the older servers.

**Comment by Frank18000** [comment]
16:05:10 XXXX to build or building queue is full!
16:05:13 XXXX 143 slinger to queue!
WARNING: 16:05:13 XXXXX wasn't found! Bot is removing it from the list of current towns.
WARNING: 16:05:13 XXXXX wasn't found! Bot is removing it from the list of current towns.

same problem as before

**Comment by BrandonWill** [comment]
Hmm, that's really strange. I haven't changed anything at all for the building queues. 

Do you mind starting on the most recent server for your language (it can be a new account) and seeing if the problem still exists? They may have changed something for their older servers

**Comment by Frank18000** [comment]
okay i will test it

**Comment by Frank18000** [comment]
i started at nl 45 and there it works after an initial error

Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
        at Grepolis.GUI.QueuePanel.saveButtonActionPerformed(QueuePanel.java:2044)
        at Grepolis.GUI.QueuePanel.access$500(QueuePanel.java:27)
        at Grepolis.GUI.QueuePanel$4.actionPerformed(QueuePanel.java:1147)
        at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
        at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
        at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
        at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
        at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
        at java.awt.Component.processMouseEvent(Unknown Source)
        at javax.swing.JComponent.processMouseEvent(Unknown Source)
        at java.awt.Component.processEvent(Unknown Source)
        at java.awt.Container.processEvent(Unknown Source)
        at java.awt.Component.dispatchEventImpl(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Window.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by Frank18000** [comment]
there is a different farm system on the new world by the way

**Comment by BrandonWill** [comment]
Yup. I'm still working on perfecting it, but the bot is able to detect and farm from it already if you've unlocked any of them. You don't need captain on the newer worlds either.

Alright, here's what you'll have to do in order for me to fix it. Log into the world that you're having problems with on google chrome.

Press control+shift+I at the same time. A console such as this should appear:

![image](https://cloud.githubusercontent.com/assets/949047/17440603/51142e06-5afb-11e6-9dfe-26747d631ba9.png)

Make sure you're on the network tab and select XHR.

Open up the senate in a town, and something like the above will pop up; this isn't what we want. Build something in the town, and you'll see two new messages popup. If you click on it, There will be a  response tab. The response you DON'T want will say something like "building order successfully made" or close to it. After you're on the right tab, click "headers".

Once on the headers, I'll need... (you can censor these as well)

![image](https://cloud.githubusercontent.com/assets/949047/17440795/1a845af4-5afc-11e6-84c8-08543e8deeed.png)

And all the query string parameters

![image](https://cloud.githubusercontent.com/assets/949047/17440834/51504340-5afc-11e6-961a-ecf8d3766266.png)

This is the stuff I get for opening up the senate, not placing an order. Yours should be different

**Comment by Frank18000** [comment]
i get the respons building built

**Comment by BrandonWill** [comment]
Alright. That may be the only response then (there's usually two). Can you post similar details that I did for opening the senate?

**Comment by BrandonWill** [comment]
It should be similar to:

![image](https://cloud.githubusercontent.com/assets/949047/17441470/38861094-5aff-11e6-8233-95c7683d79d3.png)

![image](https://cloud.githubusercontent.com/assets/949047/17441508/5d7dca7c-5aff-11e6-87d4-dd5e9a79f3fc.png)

The bot is still correctly loading the buildings, correct? Like you can see their current numbers in the queue tab after it's looked at the town.

**Comment by Frank18000** [comment]
some thing like this
yes the cities are loaded correctly. it go´s wrong after the moment the first troops are build

Request URL:https://nl40.grepolis.com/game/frontend_bridge?town_id=XXXX&action=refetch&h=44dad2211d6&json=%7B%22collections%22%3A%7B%22TownGroupTowns%22%3A%5B%5D%7D%2C%22town_id%22%3A70954%2C%22nl_init%22%3Atrue%7D&_=1470410224238
Request Method:GET
Status Code:200 Ok
Remote Address:212.53.164.49:443
Response Headers
view source
Cache-Control:no-cache
Connection:keep-alive
Content-Encoding:gzip
Content-Type:text/html; charset=utf-8
Date:Fri, 05 Aug 2016 15:17:28 GMT
Pragma:no-cache
Server:nginx
Transfer-Encoding:chunked
X-Grepo-Branch:2.117.8
X-Grepo-Revision:39666dd2355f80030204b6d5f984c43f768a3d03-55b7d42d0f9abde8f7b3b89c799bead6efd70122
X-GREPO-SCGI:1
X-JoinUs:We are always searching for skilled admins and passionate coders! Go to career.innogames.com and mention this header in your application!
Request Headers
view source
Accept:text/plain, */*; q=0.01
Accept-Encoding:gzip, deflate, sdch, br
Accept-Language:nl-NL,nl;q=0.8,en-US;q=0.6,en;q=0.4
Connection:keep-alive
Cookie:metricsUvId=aad1064d-96d8-4059-a174-8b5cd4d7edd9; cid=1463487320; toid=70954; sid=9s9twcqiifc40cwg0w4skwgk4; ig_conv_last_site=https://nl40.grepolis.com/game/index; _dc_gtm_UA-50308313-1=1; _dc_gtm_UA-13215943-7=1; _ga=GA1.3.351213833.1468512375; _ga=GA1.2.351213833.1468512375; _gat=1
Host:nl40.grepolis.com
Referer:https://nl40.grepolis.com/game/index?login=1&p=1086815&ts=1470410222
User-Agent:Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106 Safari/537.36
X-Requested-With:XMLHttpRequest
Query String Parameters
view source
view URL encoded
town_id:70954
action:refetch
h:44dad2211d6
json:{"collections":{"TownGroupTowns":[]},"town_id":XXXXX,"nl_init":true}
_:1470410224238

**Comment by BrandonWill** [comment]
That's the response for how towns are loaded.

**Comment by Frank18000** [comment]
Request URL:https://nl40.grepolis.com/game/frontend_bridge?town_id=40913&action=execute&h=0117ec67ce1
Request Method:POST
Status Code:200 Ok
Remote Address:212.53.164.49:443
Response Headers
view source
Cache-Control:no-cache
Connection:keep-alive
Content-Encoding:gzip
Content-Type:text/html; charset=utf-8
Date:Fri, 05 Aug 2016 15:38:21 GMT
Pragma:no-cache
Server:nginx
Transfer-Encoding:chunked
X-Grepo-Branch:2.117.8
X-Grepo-Revision:39666dd2355f80030204b6d5f984c43f768a3d03-55b7d42d0f9abde8f7b3b89c799bead6efd70122
X-GREPO-SCGI:1
X-JoinUs:We are always searching for skilled admins and passionate coders! Go to career.innogames.com and mention this header in your application!
Request Headers
view source
Accept:text/plain, */*; q=0.01
Accept-Encoding:gzip, deflate, br
Accept-Language:nl-NL,nl;q=0.8,en-US;q=0.6,en;q=0.4
Connection:keep-alive
Content-Length:177
Content-Type:application/x-www-form-urlencoded; charset=UTF-8
Cookie:metricsUvId=aad1064d-96d8-4059-a174-8b5cd4d7edd9; cid=1463487320; sid=1e91cxyvvl8gwkowo8owwc4ks; ig_conv_last_site=https://nl40.grepolis.com/game/index; _dc_gtm_UA-50308313-1=1; _dc_gtm_UA-13215943-7=1; _ga=GA1.3.351213833.1468512375; _ga=GA1.2.351213833.1468512375; _gat=1; toid=40913
Host:nl40.grepolis.com
Origin:https://nl40.grepolis.com
Referer:https://nl40.grepolis.com/game/index?login=1&p=1086815&ts=1470411349
User-Agent:Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106 Safari/537.36
X-Requested-With:XMLHttpRequest
Query String Parameters
view source
view URL encoded
town_id:40913
action:execute
h:0117ec67ce1
Form Data
view source
view URL encoded
json:{"model_url":"CommandsMenuBubble/1086815","action_name":"forceUpdate","arguments":{},"town_id":xxxxx,"nl_init":true}

**Comment by Frank18000** [comment]
town_id:xxxxx
action:execute
h:0117ec67ce1

**Comment by Frank18000** [comment]
this wat you wanted i think


town_id:XXXXX
action:execute
h:0117ec67ce1
Form Data
view source
view URL encoded
json:{"model_url":"BuildingOrder","action_name":"buildUp","arguments":{"building_id":"wall"},"town_id":XXXXXXX,"nl_init":true}

**Comment by BrandonWill** [comment]
Yeah that's it, but it's the same one that's already inside the bot.

**Comment by Frank18000** [comment]
okay 
end now this is the moment for panic ;-D

**Comment by BrandonWill** [comment]
Well, the bot would give you an error if it couldn't find all the buildings, but eh. Perhaps they changed the wording for everything.

Can you post the response of when you open up the senate? They may have given us less information. Right now, everything is given to us from the browser, such as if we can upgrade certain structures or not.

The latest version will also tell you everything about the buildings that it knows, which will help in my search of finding why it isn't working, ex.

![image](https://cloud.githubusercontent.com/assets/949047/17445031/f8c5fab6-5b10-11e6-86cd-c037f22a11ae.png)

**Comment by BrandonWill** [comment]
Oh uhm I didn't push it out. It'll be there soon lol

**Comment by Frank18000** [comment]
okay i will wait

**Comment by BrandonWill** [comment]
It's been released

**Comment by Frank18000** [comment]
20:19:56 Building name: lumber is building queue full: false can building be upgraded: false current level: 40 level to build to: 0 Can build: false
20:19:56 Building name: stoner is building queue full: false can building be upgraded: false current level: 40 level to build to: 0 Can build: false
20:19:56 Building name: ironer is building queue full: false can building be upgraded: false current level: 40 level to build to: 0 Can build: false
20:19:56 XXXXXX Nothing to build or building queue is full!
20:20:38 XXXXXXXX farmers are disabled!
20:21:44 XXXXXXXX wasn't found! Bot is removing it from the list of current towns.
20:21:45 XXXXXXXX wasn't found! Bot is removing it from the list of current towns.
20:21:45 XXXXX wasn't found! Bot is removing it from the list of current towns.
20:21:45 XXXXX wasn't found! Bot is removing it from the list of current towns.

i think it is my crappy connection whith the net

**Comment by BrandonWill** [comment]
Hmm. Just double check all the buildings and such that they're working correctly. The towns being found may be the cause from my auto town updater that I added recently (it's supposed to just find the town and update the resources inside the town when it's notified). I'll have a second town in a couple of days to see what's causing that

**Comment by BrandonWill** [comment]
I think you're the only one who uses this with more than 1 town lol. I finally found it and fixed it

**Comment by Frank18000** [comment]
it works

THX

**Comment by BrandonWill** [comment]
No problem! Just don't farm without captain with multiple cities. It still needs tweaking

**Comment by Frank18000** [comment]
i don't use the farming option verry often 
because i am afraid for detection ;-D

**Comment by BrandonWill** [comment]
ah alright. If you were gonna get caught, it would've happened already. They changed the url for switching towns, so the bot hasn't been switching towns correctly for who knows how long. 

It's very obvious that whoever wrote the old farming system was a professional programmer. And whoever wrote the new farming system was someone extremely new. I'm trying to get it to keep everything together... but I might just tell people to only use captain again; it's just that bad

**Comment by BrandonWill** [comment]
Like... the map gives you this:
{"id":133589,"farm_town_id":4440,"player_id":xxxx,"updated_at":1470555176,"trade_ratio":1.7,"ratio_updated_at":1470555376,"lootable_at":1470555476,"last_looted_at":1470555176,"relation_status":1,"loot":3465,"expansion_stage":2,"expansion_at":null,"lootcap_reset_at":1470607200}

where "id" represents the battle point village id. But it doesn't tell you which town it belongs to or the name of the village. So I have to search elsewhere.

{"id":4440,"name":"Doupsinos","island_x":xxx,"island_y":xxx,"island_xy":xxx,"chunks_x":"{xx}","chunks_y":"{xx}","number_on_island":2,"resource_offer":"iron","resource_demand":"wood"}

Here, "id" represents what farm_town_id above represented. Why they did this, who knows? But this just tells you the name of the village. I have to use the island x and island y to map it to the town it belongs to.

Which comes to the next fun part, they reuse farm town ids and they change for towns. It's just really annoying, but I don't wanna pay for captain lol

**Comment by Frank18000** [comment]
i have to test some more but i see some town names changing

**Comment by BrandonWill** [comment]
Can you post what the names are changing from/to? You can edit it out right after; it'll get sent to my email

**Comment by BrandonWill** [comment]
I did notice on some world's with accents on letters and such, the bot reads them really weird. 

Should I just look for name changes when it first runs instead of trying to actively update the name?

**Comment by BrandonWill** [comment]
Went ahead and did that. Town names will update whenever you start the bot. It only started doing it because the bot needed to know the wood/stone/silver for captainless farming.

**Comment by Frank18000** [comment]
this works i have tested it on an account with 200+ cities
The only thing i saw is tha 2 cities were renamed to kolonisatie schip and katapult

**Comment by BrandonWill** [comment]
Hmm. I assume it still builds everything though?

I might have to scratch the whole last_wood idea. I've had a couple of really weird bugs come up like having the same town show up twice

**Comment by Frank18000** [comment]
that´s wat i see some citys sow up twice etc.

Building it does

**Comment by BrandonWill** [comment]
Alright. I put out a new version. It should only update resources from now on. Duplicates shouldn't be possible. Let me know how it works

**Comment by Frank18000** [comment]
it works great cultural i didn´t see

**Comment by BrandonWill** [comment]
It wouldn't happen on the first go around. The game sends "notifications" to peoples browser to update their resources. And it would work then. It did this so it didn't open up the agora every time to check.

I can make it always check, so it will work everytime if you want me to

**Comment by Frank18000** [comment]
i use the bot primairely for building not for farming. So for me it is not nessary

**Comment by BrandonWill** [comment]
Alright. I probably won't try to fix it then. It works correctly when you have captain though. 

I probably won't get research/attack/defense done this go around. I'm trying to make sure everything is stable before my classes start back up

**Comment by Frank18000** [comment]
great 
i can´t wait for that options but school is more important

**Comment by BrandonWill** [comment]
Yeah. I'll have to do some special things to get attack/defense working. Research will come before that so I can be lazy when starting up a city (like just leaving it run for a week while it does everything)

**Comment by Frank18000** [comment]
LOL

**Comment by BrandonWill** [comment]
That's what I'm doing on the nl server lol. I keep getting slapped by some big alliance. I'm sitting on 2k LDU in each of my cities just thinking wtf are these guys doing. I have tower and lvl 25 walls in all of them

**Comment by Frank18000** [comment]
on witch server are you?

**Comment by BrandonWill** [comment]
nl46

**Comment by Frank18000** [comment]
that is the newest server. I have started there for testing. But i am not gonne play there

**Comment by BrandonWill** [comment]
Yeah. I'm probably not going to play it much longer. I started it so I could find out what weird bug you had
