### ISSUE TITLE
Farming issue

### ISSUE THREAD

**Issue by beaubeire** [BrandonWill/GrepolisBot#12]
Your farming system doesn't work on a world with those new farming villages when you research the technology "Villagers loyalty"

**Comment by BrandonWill** [comment]
Does the research just double the time it's going to take to farm the villages?

**Comment by BrandonWill** [comment]
This might be awhile since the only way to detect this is to find the research for every town

**Comment by beaubeire** [comment]
Can't you just make an option to farm for 10m instead of 5m? Will it solve the problem that way?

**Comment by BrandonWill** [comment]
I could, but it'd cause more problems than it'd be worth. Every town you have would have to have the option along with it being saved/loaded. Hours of work for something that'll be replaced soon (I'm planning on letting you automatically research everything). I'll try to see if I can find a short term automatic fix after work today

**Comment by BrandonWill** [comment]
The new farming also needs a lot more work put into it. You can farm less resources per day before upgrading now. It's probably automatically fixed if you have captain and doesn't let you farm it, but for non-captain users there will be issues.

**Comment by BrandonWill** [comment]
Alright I'm off to work, but I attempted a fix. Try it out and let me know if it works, but keep your old .jar file in case it breaks everything since I haven't tested it.

**Comment by beaubeire** [comment]
Tried it out and doesn't work.

**Comment by BrandonWill** [comment]
Alright. And you're using captain, correct? The fix I sent was for captain. I believe it should work correctly for non-captain users due to it giving difference information. 

I still have about 5 hours until academy level 7 is complete and then I can work on a solution.

**Comment by BrandonWill** [comment]
The problem is that I have no idea how they coded it. When I read the data, it still shows researches that aren't available such as booty and diplomacy. So they have the research shown as "villagers loyalty" to users, but it's something completely different on the backend

**Comment by BrandonWill** [comment]
This issue should now be fixed. Everything now looks at current server time. Make sure your computer clock is correct though (it converts it to UTC time and then into unix time)!

**Comment by BrandonWill** [comment]
Working on it now that I have it researched.

**Comment by BrandonWill** [comment]
Fixed for captainless farming. It'd still be broken if you were using captain though because I haven't unlocked it yet on my current account.
