### ISSUE TITLE
Login without browser script

### ISSUE THREAD

**Issue by govindlahoti** [BrandonWill/GrepolisBot#13]
Is it possible to login without executing the script in browser?
I mean is it possible to login and obtain the SID cookie just by sending POST request to https://us.grepolis.com/glps/login_check

Thanks

**Comment by BrandonWill** [comment]
Yes for the first question. The previous bot (the one in the readme) actually did just that; it simply gave the users a browser to play on if they wished. I'd suggest using Apache's HttpClient if you were to do this in Java. 

For the second question, SID cookies are used by Google to give ads. I'm not sure if that's what you're looking for? If you mean regular cookies so you don't have to enter in your username/password every time, then yes they can be obtained. It's usually easier to just look how they're made and generate them yourself though.

**Comment by govindlahoti** [comment]
Thanks :)
