### ISSUE TITLE
farming

### ISSUE THREAD

**Issue by allessi10** [BrandonWill/GrepolisBot#16]
Any way i can disable the "plunder" option that takes mood from the villages? Like i want to use the second option to farm without it taking the mood from the villages.

**Comment by BrandonWill** [comment]
It'll lower the mood to the village to the value that you set it to. If you never want it to lower the mood, simply set it to the max mood (100)

**Comment by allessi10** [comment]
i just saw that in the update thread. My bad! Thanks for helping though!
