### ISSUE TITLE
Farming

### ISSUE THREAD

**Issue by allessi10** [BrandonWill/GrepolisBot#17]
I can't configure some towns to not farm, like when i have more towns on one island i only want one town to farm.

**Comment by BrandonWill** [comment]
Are you setting up your towns like this? You have to disable farming for all towns on the left and then go to the town you don't want to farm in and disable it. Make sure you save it as well.

![image](https://cloud.githubusercontent.com/assets/949047/18525552/fa87438e-7a8a-11e6-8e60-6aaf0d2d9aac.png)

**Comment by BrandonWill** [comment]
When you have multiple towns on the same island, you have to change all farming individually. However, you can still edit them all by clicking "update all towns" on the right.

**Comment by allessi10** [comment]
Yea im just retarded. Thanks

**Comment by BrandonWill** [comment]
Not sure if sarcasm or...

I just noticed that the bot isn't loading the "all town" setting correctly as well. So right now it always starts up as enabled every time you load the bot regardless of what the save file says. I'll look into a fix on Friday
