### ISSUE TITLE
Error! Can't find the towns with farms! Error log: TownFarmingData:0

### ISSUE THREAD

**Issue by Marcoglione** [BrandonWill/GrepolisBot#18]
Hi enthusiastic work friends

I can not FARM.
I am using Mozilla Firefoz 49.02, Win 7 Ultimate 32 bits
here the log of version 0.20

**12:02:35 Selecting world
12:02:43 Selecting world
12:02:48 Selecting world
12:03:44 csrftoken: 7d966ed19f7
12:03:44 Default town: 70423
12:17:49 Towns found: 1
12:41:38 Error! Was unable to load the farming villages from the map! Error log: LoadedVillagesFromMap:0**

append the a picture where you can see the only town that show (and not working any selections)
and I can not change to others town.
![untitled](https://cloud.githubusercontent.com/assets/23105281/19779585/b36f56c6-9c4f-11e6-9b65-503c52fee980.jpg)

in any line of your conversations I seemed to see that there is a version that corrects this.
I  hope you can guide me to reach a solution,...
Regards
Marco

**Comment by BrandonWill** [comment]
Are you playing on a server with battle point villages? Farming without captain only worked on those worlds

**Comment by Marcoglione** [comment]
Hi,
You are right.
I need Captain active.
Ty

⁣---Marco ​
