### ISSUE TITLE
farming

### ISSUE THREAD

**Issue by Frank18000** [BrandonWill/GrepolisBot#19]
Farming doesn't work annymore. Kaptain is activeted but the bot says it isn't

**Comment by BrandonWill** [comment]
Did you restart the bot after activating captain?

**Comment by Frank18000** [comment]
yes the captain was activated before i started the captain

**Comment by BrandonWill** [comment]
Alright. I'll try to look into it later tonight. What server are you playing on?

**Comment by Frank18000** [comment]
farsala nl51

**Comment by BrandonWill** [comment]
Good to know! The bot works by grabbing the expiration time and comparing it to the current time that your system has. However, it only does this once the bot is started. If captain is purchased afterwards, the whole thing has to be restarted
