### ISSUE TITLE
Only towns with farming villages are loaded

### ISSUE THREAD

**Issue by BrandonWill** [BrandonWill/GrepolisBot#2]

**Comment by Frank18000** [comment]
in the kapteins vieuw only the villages with farms are visseble 
when the bot looks ther fore villages he misses the villages without farms

**Comment by BrandonWill** [comment]
Well, it loads the towns from the captain overview. It would miss all the towns that didn't have farms.

There's other ways to load towns though. I'll look into implementing another way when I have more free time

**Comment by Frank18000** [comment]
okay great
mayby is splitting the cycle of building and troops from the farming cycle also a good thing

**Comment by BrandonWill** [comment]
It wouldn't be hard to separate them.

I'm busy with classes and work for now. I'll get around to this current issue hopefully in the next week.

Let me know if the bot breaks in the meantime. T normally doesn't take more than 10mins to update anything that breaks

**Comment by Frank18000** [comment]
when the Bot brakes down i will inform you.
Real life is far more importend

**Comment by BrandonWill** [comment]
Issue should be fixed in the most recent version!
