### ISSUE TITLE
Black page on browser tab on specific domain?

### ISSUE THREAD

**Issue by Spammaren** [BrandonWill/GrepolisBot#20]
Hello!
I am trying to use your bot on the Swedish version of Grepolis. However, whenever I try to open the website through the browser tab in the bot it's all just black and only the top row is shown. [Screenshot for clarity.](http://i.imgur.com/2itb8nL.png) On every other domain I've tested, (.en, .dk, .fr, .de, you name it.) it works just fine. 

What might be the issue?

**Comment by BrandonWill** [comment]
Has it ever worked on Sweden server? The Sweden page looks as if it's using the login page from about 2 years ago, so there's a chance they forgot to update it lol

**Comment by mj9999** [comment]
this is happening now on other world EN . US 
the bot isnt logging to the game and stays on the entering page when only the upper title is shown while everything else is black

**Comment by Darkosz** [comment]
Same on the Hungarian server :/

**Comment by KubilayEser** [comment]
Same on the Turkish server. Please help :/

**Comment by BetaWing** [comment]
Happening on Portuguese server too. Hope you can fix it ASAP. Keep up the great work BrandoWill

**Comment by BrandonWill** [comment]
I've messed with it for about 2 hours and I can't figure out what they've done this time to stop bots from logging in.

I've released a new version that just loads the page. You have to enter in the login details and click the button yourself. The bot will auto-select the world and it'll work like before. 

I'll look into actually fixing it later, but this at least allows you guys to have a bot

**Comment by BrandonWill** [comment]
Login is now automatic again. Happy botting!

**Comment by mj9999** [comment]
many thanks !!
