### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by izanbf1803** [BrandonWill/GrepolisBot#23]
Web view login not working (Post request always loading).

**Comment by Spammaren** [comment]
Works for me on the english server.

**Comment by izanbf1803** [comment]
Ok, i'm trying to connect to the spanish server, but is not working.

**Comment by BrandonWill** [comment]
Tried the bot on the most recent Spanish server, es63, and it works for me. If it's still an issue for you, then please open the issue back up!

**Comment by BrandonWill** [comment]
This works fine for me on Windows 7, but it runs into a problem on Windows 8... if you right click and click refresh after it tries to log in, it will work as normal. I'm not sure why this is a problem
