### ISSUE TITLE
Doent work

### ISSUE THREAD

**Issue by qwerty9797** [BrandonWill/GrepolisBot#25]
why i cant see the browser button? ahah

**Comment by BrandonWill** [comment]
I'm not sure why it doesn't work for you. You seem to be only one with the issue. If your computer is slow, it may take awhile for the browser tab to popup.

**Comment by qwerty9797** [comment]
The "browser" windows isn't presente in the bot menu!

Il giovedì 18 maggio 2017, BrandonWill <notifications@github.com> ha
scritto:

**Comment by BrandonWill** [comment]
If you run the bot from the run.bat file, is there an error?

**Comment by nikitozzz** [comment]
how run in linux?

**Comment by BrandonWill** [comment]
I haven't tested the bot in linux, but everything in the bot is purely Java. It should be compatible. 

The batch file just contains "java -jar GrepolisBot_0.22.jar", which is also valid in the linux terminal. You'd have to cd into the directory of the bot and run it from there.
