### ISSUE TITLE
Error Farming interval

### ISSUE THREAD

**Issue by lusuma** [BrandonWill/GrepolisBot#26]
Error in Farming Settings.
With Academy level 10, investigated booty, no Captain, error occurs in the farming range. Appears 5 - 20 minutes and 1:30 - 4 hours; instead of 10 - 40 minutes and 3 - 8 hours.

**Comment by BrandonWill** [comment]
If you have it researched, the bot will automatically convert it behind the scenes

**Comment by BrandonWill** [comment]
I did push out a change today though that allowed the other options to work with booty though. Beforehand, only the 5/10 minute farming worked

**Comment by lusuma** [comment]
Good job. Thank you very much for your effort.
