### ISSUE TITLE
Browser sound

### ISSUE THREAD

**Issue by lusuma** [BrandonWill/GrepolisBot#27]
You can not activate the Browser sound. Is mute.

**Comment by BrandonWill** [comment]
Sound works for me with these settings.

![image](https://cloud.githubusercontent.com/assets/949047/26216435/171dc00a-3bd2-11e7-83b5-a38df78b6ba7.png)

Is that the settings that you have?

**Comment by lusuma** [comment]
You can close the issue. It's my mistake.
Excuse me
