### ISSUE TITLE
Can't find variable: Jquerry

### ISSUE THREAD

**Issue by martinez228** [BrandonWill/GrepolisBot#4]
Hello Brandom,
when the Bot start I see a Exception in Thread, with information that Can't find Jquerry.

I have one town with 4 farms, but the bot show Towns found:1, Towns with farms found:0

I play on en88 server and the bot doesn't work

**Comment by BrandonWill** [comment]
You have to post the full error for future references. 

The bot requires you to have captain if you'd like to use the farming feature. It won't find towns with farms without it.
